spring:
  profiles: 
    active: 
    - dev
    
---
spring: 
  profiles: dev		#测试环境
  application: 
    name: microservicecloud-config-lvyang-dev

---
spring:
  profiles: test
  application: 
    name: microservicecloud-config-lvyang-test
    
#请保存为UTF-8格式